baseURL = "https://lovkush.com/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Lovkush 🔸"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

# Automatically set last modified dates using Git commit dates
enableGitInfo = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/Lovkush-A/website"
    weight = 4
    pre = "<span data-feather='github'></span>"

  [[menu.main]]
    name = "About"
    url = "/about-me/"
    weight = 1


[params]
  dateFormat = "January 2, 2006"
  footer = ""
  description = """Mathematician → Lecturer → Data Scientist → AI Safety Researcher"""
    socialIcons = [
    {name = "twitter", url = "https://twitter.com/lovkushatleeds"},
    {name = "linkedin", url = "https://www.linkedin.com/in/lovkush-agarwal-%F0%9F%94%B8-481737131/"},
  ]
  metaKeywords = ["blog", "lovkush", "Lovkush", "agarwal", "Agarwal", "ai safety", "teaching", "ai"]
  customHeadHTML = '''
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css" integrity="sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js" integrity="sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js" integrity="sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
    <script type='module' src='https://js.withorbit.com/orbit-web-component.js'></script>
  '''
